### ISSUE TITLE
Font/window size

### ISSUE THREAD

**Issue by omid** [Iaphetes/aphorme_launcher#2]
It looks too small in my screen.
I couldn't find any option to make the font or generally the window bigger.

It would be nice if we have them.

**Comment by Iaphetes** [comment]
I'll have a look at this the coming week.

Window size should be relatively trivial. Font is a bit more complex, since the icon size depends on the font size as well.

**Comment by Iaphetes** [comment]
OKay was easier than thought. The feature is available in 0.1.19
