### ISSUE TITLE
Aphorme does not find *.desktop files generated/linked by nix-community/home-manager.

### ISSUE THREAD

**Issue by Sntx626** [Iaphetes/aphorme_launcher#8]
The path in question is:

```
~/.local/state/home-manager/gcroots/current-home/home-path/share/applications
```

Adding the path to Aphormes' default paths would allow it to display applications to NixOS users that use home-manager to configure their userspace applications.

I can open up a PR in case this is wanted.

**Comment by Iaphetes** [comment]
Hi,

I can add that to the default paths.
In the mean time, what speaks against adding it to the 'paths' config?

**Comment by Sntx626** [comment]
Hi!

> In the mean time, what speaks against adding it to the 'paths' config?

Nothing speaks against it, thanks for the hint ^^

Though adding it as a default path would improve the onboarding experience for some users, since you want to try it out first and then configure it.

**Comment by Iaphetes** [comment]
Hi,

ah okay. I just made a commit appending the path to the default paths. I release a new version, once @AnyTimeTraveler had time to look over the nix changes.
